### ISSUE TITLE
[Feat] 지도 페이지 UI구현

### ISSUE THREAD

**Issue by Whited123** [NBCAMP-ToDwoong/todwoong#51]
## 어떤 기능인가요?

> 지도 페이지 UI 작업입니다.

## 작업 상세 내용

- [x] 상단 네비게이션 아이템 세팅(back버튼, 내 현재 위치로 이동 버튼, 투명하게 세팅하여 지도 시야 확장)
- [x] 네비게이션 아이템 밑에 카테고리 칩버튼 추가
- [x] 지도 추가
- [x] 모달창 테이블뷰 세팅

**Comment by yenny42** [comment]
기능과 ui는 분리해서 이슈 생성해주세요
